# Generated by Django 4.1.6 on 2023-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_remove_ghuser_url_ghuser_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghrepository',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
