# Generated by Django 4.1.6 on 2023-08-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_ghrepositorygroup_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghrepositorygroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
