# Generated by Django 4.1.6 on 2023-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_alter_ghrepositorygroup_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghrepositorygroup',
            name='recommended_repositories',
            field=models.ManyToManyField(through='recommendations.GHRecommendedRepository', to='recommendations.ghrepository'),
        ),
    ]
