# Generated by Django 4.1.6 on 2023-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0016_remove_ghrepository_id_alter_ghrepository_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ghrepository",
            name="url",
            field=models.URLField(max_length=2100, unique=True),
        ),
        migrations.AddField(
            model_name="ghrepository",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
    ]
