# Generated by Django 5.0a1 on 2023-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0017_ghrepository_id_alter_ghrepository_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.AddField(
            model_name="ghuser",
            name="retrieve_reps_task_id",
            field=models.UUIDField(null=True),
        ),
    ]
