# Generated by Django 5.0a1 on 2023-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0018_delete_customer_ghuser_retrieve_reps_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ghrepositorygroup",
            name="get_recs_task_id",
            field=models.UUIDField(null=True),
        ),
    ]
