# Generated by Django 5.0a1 on 2023-12-14 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0020_alter_ghrecommendedrepository_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ghrecommendedrepository",
            options={"ordering": ["-num_of_hits", "repository__num_stars", "pk"]},
        ),
    ]
